### ISSUE TITLE
User Story - View all subs

### ISSUE THREAD

**Issue by raymondkeogh** [raymondkeogh/subhub#2]
1. **As a** Principal 
1. **I want** to see all subs
1. **so that** I can see the names in a list
#Acceptance Criteria
*Acceptance Criteria 1: After logging in a list of subs are displayed on the screen with a grid view
*Acceptance Criteria 2: The name, email and phone number, subjects and availabiliy are visible.

**Comment by Fiona-T** [comment]
Columns are added in index.html. Just to test once the new fields are working properly in the model

**Comment by Fiona-T** [comment]
All fields now coming back in view - closed
