### ISSUE TITLE
User Story - Sort subs list

### ISSUE THREAD

**Issue by raymondkeogh** [raymondkeogh/subhub#3]
1. **As a** Principal
1. **I want** to be able to sort the list of subs 
1. **so that** so that I can view based on chosen criteria, name and availability
#Acceptance Criteria
*Acceptance Criteria 1: When I click on the sub name list header I can change the sort order of the list alphabetically 
*Acceptance Criteria 2: When I click on the availability I can sort the list based on availability.

**Comment by Fiona-T** [comment]
Sorting by name is already done. To implement: sorting by availability, once this is coming back from the database

**Comment by Fiona-T** [comment]
Tested - sort works on first name, last name, subject and Availability. Closed
