### ISSUE TITLE
User Story - Filter by subject

### ISSUE THREAD

**Issue by raymondkeogh** [raymondkeogh/subhub#4]
1. **As a** Principal
1. **I want** I want to be able to filter the list of subs by subject.
1. **so that** I can see subs in a chosen field.
#Acceptance Criteria
*Acceptance Criteria 1: Clicking on a dropdown menu above the subs list with show a list of subjects.
*Acceptance Criteria 2: Clicking on a subject in the dropdown menu will filter the list by subject.

**Comment by Fiona-T** [comment]
Styling to be added for the filters in index.html. Sorting needs to be fixed up, to include the selected filter if possible

**Comment by Fiona-T** [comment]
Added All option, so can go back to the full table after previously filtering. Ray has added the links into dropdown and table sorted changed to sort by js so now works with filtering. Closed
